[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
gas_reports = ['*']
solc_version = "0.8.34"
optimizer = true
optimizer_runs = 200
ffi = true
ast = true
build_info = true
dynamic_test_linking = false
fs_permissions = [{ access = "read-write", path = "." }]
evm_version = "cancun"

[profile.deploy]
solc_version = "0.8.34"
optimizer = true
optimizer_runs = 200

[profile.solx]
gas_limit = 100_000_000

[lint]
exclude_lints = ["mixed-case-function","screaming-snake-case-immutable","pascal-case-struct", "mixed-case-variable", "unsafe-cheatcode"]
ignore = ["src/vendor/**/*"]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
sort_imports = true

[doc]
out = "foundry-docs/"
title = "MetaWallet Contracts Documentation"

[dependencies]
minimal-smart-account = { version = "1.0", git = "https://github.com/turingcapitalgroup/minimal-smart-account.git", rev = "0fd060740a7d929b56cff6f73350a19179612ac4"}
forge-std = "1.11.0"
kam = { version = "1.0", git = "https://github.com/turingcapitalgroup/kam.git", rev = "78ea3deb116775665efa1efdba2054ddca80813f" }
minimal-uups-factory = { version = "1.0.0", git = "https://github.com/turingcapitalgroup/minimal-uups-factory.git", rev = "568d85a0921f5b0bc7c410d99363cebdd0cd2ee5" }

[soldeer]
# whether soldeer manages remappings
remappings_generated = false
# whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false
# whether to suffix the remapping with the version: `name-a.b.c`
remappings_version = false
